version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "Demeter2023"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=Demeter2023
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge
