name: Deploy on Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build-api:
    name: Build Docker image - Core API
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/VnRoadSide/RoadSide/roadside-api
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          file: src/RoadSide.Web/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

  redeploy:
    name: Build Docker image - Core API
    runs-on: ubuntu-latest

    needs: build-api

    permissions:
      contents: read
      packages: write

    steps:
      - run: sudo apt install --install-suggests wireguard
      - run: echo "${{ secrets.WG_CONF }}" > ./github-action.conf
      - run: wg-quick up ./github-action.conf
      - run: echo "${{ secrets.SSH_PRIVKEY }}" > ./ssh-key | ssh -i ./ssh-key ducth@192.168.0.65 'cd ~/RoadSide && git fetch && git pull && docker compose -f docker-compose.prod.yaml up -d'
      - run: wg-quick down ./github-action.conf